### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by iraizo** [jbszczepaniak/spotify-cli#16]
if im starting spotify-cli it opens the auth request, but fails with `INVALID_CLIENT: Invalid redirect URI`

**Comment by andrewtakeshi** [comment]
Hey! I ran into the same issue and it turned out to be the case that I'm just bad at reading instructions. Under the app you create in the spotify developer dashboard, you need to go to the app settings and make sure you have one of the whitelisted callback URL's set to http://localhost:8888/spotify-cli. After I changed that it started working for me.
